#"Diagnosis", "radius", "texture", "perimeter", "area", "smoothness", "compactness", "concavity", "concave points", "symmetry", "fractal"
#"Diagnosis_SE", "radius_SE", "texture_SE", "perimeter_SE", "area_SE", "smoothness_SE", "compactness_SE", "concavity_SE", "concave points_SE", "symmetry_SE", "fractal_SE"
#"Diagnosis_Worst", "radius_Worst", "texture_Worst", "perimeter_Worst", "area_Worst", "smoothness_Worst", "compactness_Worst", "concavity_Worst", "concave points_Worst", "symmetry_Worst", "fractal_Worst"
features:
  - "radius"
  - "texture"
  - "perimeter"
  - "area"
  - "smoothness"
  - "compactness"
  - "concavity"
  - "concave points"
  - "symmetry"
  - "fractal"